# Generated by Django 4.0.3 on 2022-03-20 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Peril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('dataNascimento', models.DateField()),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.imagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
